import { beforeEach, describe, expect, it } from 'vitest'
import { normalizeCanvasTransform } from '@/core/layer-transform'
import type { VideoItem } from '@/types'
import { useEditorStore } from './editorStore'

const state = () => useEditorStore.getState()
const createVideo = (name = 'avatar'): VideoItem => ({
  movie: {
    version: '2.0',
    params: { viewBoxWidth: 400, viewBoxHeight: 300, fps: 24, frames: 24 },
    images: {},
    sprites: [{
      imageKey: name,
      matteKey: null,
      frames: Array.from({ length: 24 }, (_, index) => ({
        alpha: 1,
        layout: { x: 0, y: 0, width: 80, height: 60 },
        transform: { a: 1, b: 0, c: 0, d: 1, tx: index * 3, ty: index * 2 },
        clipPath: null
      }))
    }]
  },
  images: {},
  buffers: { [name]: new Uint8Array([1, 2, 3]).buffer }
})

const makeEdits = () => {
  state().updateLayer('0', { opacity: 0.8 })
  state().setCustomFrames(12)
  state().setCustomFps(60)
}

const allLabels = () => [...state().history.past, ...state().history.future].map(entry => entry.label)
const openSnapshotId = () => state().history.snapshots![0].id

beforeEach(() => {
  state().reset()
  useEditorStore.setState({ history: { ...state().history, maxDepth: 100 } })
  state().setVideoItem(createVideo())
  state().setOriginalBuffer(new ArrayBuffer(16))
  state().selectLayer('0')
  state().addImageResource({ key: 'avatar', data: new Uint8Array([1, 2, 3]), width: 80, height: 60, mimeType: 'image/png' })
  state().addAudioResource({ key: 'music', data: new Uint8Array([4, 5]), startTime: 0, duration: 1000 })
  state().initializeHistory()
})

describe('历史记录面板的时间线', () => {
  it('导入完成时建立完整、干净的打开状态和独立打开快照', () => {
    expect(state().history.baseLabel).toBe('打开')
    expect(state().history.past).toEqual([])
    expect(state().history.future).toEqual([])
    expect(state().history.snapshots).toHaveLength(1)
    const opened = state().history.snapshots![0]
    expect(opened.name).toBe('打开')
    expect(opened.snapshot.layers[0].imageKey).toBe('avatar')
    expect(opened.snapshot.imageResources.get('avatar')!.data).toEqual(new Uint8Array([1, 2, 3]))
    expect(opened.snapshot.audioResources.get('music')!.duration).toBe(1000)
    expect(state().isDirty).toBe(false)
    expect(state().canUndo).toBe(false)
    expect(state().canRedo).toBe(false)
  })

  it('多步前后跳转只应用一次目标状态，所有步骤名称始终对齐', () => {
    makeEdits()
    const labels = ['修改图层属性：avatar', '修改总帧数', '修改帧率']
    let updates = 0
    const unsubscribe = useEditorStore.subscribe(() => { updates++ })
    state().jumpToHistory(0)
    unsubscribe()
    expect(updates).toBe(1)
    expect(state().layers[0].opacity).toBe(1)
    expect(state().customFrames).toBeNull()
    expect(state().customFps).toBeNull()
    expect(state().canUndo).toBe(false)
    expect(state().canRedo).toBe(true)
    expect(allLabels()).toEqual(labels)
    state().jumpToHistory(2)
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().customFrames).toBe(12)
    expect(state().customFps).toBeNull()
    expect(state().history.past.map(entry => entry.label)).toEqual(labels.slice(0, 2))
    expect(state().history.future[0].label).toBe(labels[2])
    state().jumpToHistory(3)
    expect(state().customFps).toBe(60)
    expect(state().canRedo).toBe(false)
    state().undo()
    expect(state().history.future[0].label).toBe(labels[2])
    state().redo()
    expect(state().customFps).toBe(60)
    expect(allLabels()).toEqual(labels)
  })

  it('无变化编辑、播放和选择操作不会破坏未来步骤', () => {
    makeEdits()
    state().jumpToHistory(0)
    const history = state().history
    state().updateLayer('0', { opacity: 1 })
    state().setCustomFrames(null)
    state().selectLayer(null)
    state().selectLayer('0')
    state().setCurrentFrame(10)
    state().setSpeed(2)
    state().setPlaying(true)
    state().setPreviewBackgroundColor('#000000')
    expect(state().history).toBe(history)
    expect(state().canRedo).toBe(true)
    state().jumpToHistory(3)
    expect(state().customFps).toBe(60)
  })

  it('干净文档上的无变化操作不标脏，真实分支才移除未来记录', () => {
    state().updateLayer('0', { opacity: 1 })
    expect(state().isDirty).toBe(false)
    makeEdits()
    state().jumpToHistory(1)
    state().updateLayer('0', { name: 'new-avatar' })
    expect(state().history.future).toEqual([])
    expect(allLabels()).toEqual(['修改图层属性：avatar', '重命名图层：avatar'])
    expect(state().customFrames).toBeNull()
    expect(state().canRedo).toBe(false)
  })

  it('超出历史上限后基线名称与保留的状态一致，打开快照仍然可用', () => {
    useEditorStore.setState({ history: { ...state().history, maxDepth: 2 } })
    makeEdits()
    expect(state().history.past).toHaveLength(2)
    expect(state().history.baseLabel).toBe('修改图层属性：avatar')
    expect(allLabels()).toEqual(['修改总帧数', '修改帧率'])
    state().jumpToHistory(0)
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().customFrames).toBeNull()
    state().jumpToHistory(2)
    expect(state().customFps).toBe(60)
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().layers[0].opacity).toBe(1)
    expect(state().customFps).toBeNull()
  })

  it('拒绝非法索引，点击当前状态只暂停播放', () => {
    makeEdits()
    const before = state()
    for (const index of [-1, 4, 1.5, NaN, Infinity]) state().jumpToHistory(index)
    expect(state()).toBe(before)
    state().setPlaying(true)
    state().jumpToHistory(3)
    expect(state().history).toBe(before.history)
    expect(state().playback.isPlaying).toBe(false)
  })

  it('删除一个历史状态会回到前一步，并移除它及后续记录', () => {
    makeEdits()
    const snapshots = state().history.snapshots
    state().deleteHistoryState(2)
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().customFrames).toBeNull()
    expect(state().customFps).toBeNull()
    expect(allLabels()).toEqual(['修改图层属性：avatar'])
    expect(state().history.future).toEqual([])
    expect(state().history.snapshots).toBe(snapshots)
    state().undo()
    expect(state().layers[0].opacity).toBe(1)
    state().redo()
    expect(state().layers[0].opacity).toBe(0.8)
  })

  it('允许删除未来状态，禁止删除基线或不存在的步骤', () => {
    makeEdits()
    state().jumpToHistory(0)
    const before = state()
    for (const index of [0, -1, 4, 1.5, NaN]) state().deleteHistoryState(index)
    expect(state()).toBe(before)
    state().deleteHistoryState(3)
    expect(state().history.past).toHaveLength(2)
    expect(state().history.future).toHaveLength(0)
    expect(state().customFrames).toBe(12)
    expect(state().customFps).toBeNull()
  })

  it('清空历史保留当前文档及所有快照，当前画面成为新基线', () => {
    makeEdits()
    state().createHistorySnapshot('修改完成')
    const before = state()
    state().clearHistory()
    expect(state().layers).toBe(before.layers)
    expect(state().history.snapshots).toBe(before.history.snapshots)
    expect(state().history.baseLabel).toBe('清空后的状态')
    expect(state().canUndo).toBe(false)
    expect(state().canRedo).toBe(false)
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().layers[0].opacity).toBe(1)
    state().undo()
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().customFps).toBe(60)
    expect(state().history.baseLabel).toBe('清空后的状态')
  })
})

describe('历史快照与时间线隔离', () => {
  it('干净打开状态浏览同内容快照及返回基线不标脏，也不重建文档对象', () => {
    const before = state()
    const opened = openSnapshotId()
    state().restoreHistorySnapshot(opened)
    expect(state().isDirty).toBe(false)
    expect(state().layers).toBe(before.layers)
    expect(state().params).toBe(before.params)
    expect(state().imageResources).toBe(before.imageResources)
    expect(state().audioResources).toBe(before.audioResources)
    expect(state().playback).toBe(before.playback)
    const restored = state()
    state().restoreHistorySnapshot(opened)
    expect(state()).toBe(restored)
    state().undo()
    expect(state().isDirty).toBe(false)
    expect(state().layers).toBe(before.layers)
    expect(state().imageResources).toBe(before.imageResources)
    expect(state().history.activeSnapshotId).toBeNull()
    state().jumpToHistory(0)
    expect(state().isDirty).toBe(false)
  })

  it('快照仅恢复选择或暂停播放时保持干净，不改变文档资源引用', () => {
    state().selectLayer(null)
    state().setPlaying(true)
    const before = state()
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().selectedLayerId).toBe('0')
    expect(state().playback.isPlaying).toBe(false)
    expect(state().isDirty).toBe(false)
    expect(state().layers).toBe(before.layers)
    expect(state().imageResources).toBe(before.imageResources)
    state().jumpToHistory(0)
    expect(state().selectedLayerId).toBeNull()
    expect(state().isDirty).toBe(false)
  })

  it.each([true, false])('同内容快照保留已有 dirty=%s，重复点击是完全无操作', dirty => {
    makeEdits()
    const first = state().createHistorySnapshot('相同内容一')
    const second = state().createHistorySnapshot('相同内容二')
    useEditorStore.setState({ isDirty: dirty })
    const layers = state().layers
    state().restoreHistorySnapshot(first)
    state().restoreHistorySnapshot(second)
    expect(state().isDirty).toBe(dirty)
    expect(state().layers).toBe(layers)
    const before = state()
    state().restoreHistorySnapshot(second)
    expect(state()).toBe(before)
  })

  it('浏览另一内容的快照并保存后，返回原时间线不能错误恢复旧的干净标记', () => {
    makeEdits()
    useEditorStore.setState({ isDirty: false })
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().isDirty).toBe(true)
    useEditorStore.setState({ isDirty: false })
    state().undo()
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().isDirty).toBe(true)
  })

  it('创建、命名及浏览多个快照均不追加历史，也不覆盖原时间线', () => {
    state().updateLayer('0', { opacity: 0.8 })
    const firstId = state().createHistorySnapshot('  中间状态  ')
    state().setCustomFrames(12)
    const secondId = state().createHistorySnapshot()
    expect(state().history.snapshots!.map(snapshot => snapshot.name)).toEqual(['打开', '中间状态', '快照 1'])
    const before = state().history
    state().restoreHistorySnapshot(firstId)
    const timeline = state().history.timelineSnapshot
    expect(state().customFrames).toBeNull()
    expect(state().history.past).toBe(before.past)
    expect(state().history.future).toBe(before.future)
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().layers[0].opacity).toBe(1)
    state().restoreHistorySnapshot(secondId)
    expect(state().customFrames).toBe(12)
    expect(state().history.timelineSnapshot).toBe(timeline)
    state().jumpToHistory(1)
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().customFrames).toBeNull()
    expect(state().history.activeSnapshotId).toBeNull()
    expect(state().history.timelineSnapshot).toBeNull()
    state().jumpToHistory(2)
    expect(state().customFrames).toBe(12)
  })

  it('快照状态撤销返回原时间线当前位置，重做在快照状态不移动', () => {
    makeEdits()
    state().jumpToHistory(1)
    const before = state().history
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().canUndo).toBe(true)
    expect(state().canRedo).toBe(false)
    const restored = state()
    state().redo()
    expect(state()).toBe(restored)
    state().undo()
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().history.past).toEqual(before.past)
    expect(state().history.future).toEqual(before.future)
    expect(state().canRedo).toBe(true)
    state().redo()
    expect(state().customFrames).toBe(12)
  })

  it('快照上的无变化动作保持原时间线，真实新编辑则从快照开始新分支', () => {
    makeEdits()
    state().restoreHistorySnapshot(openSnapshotId())
    const before = state().history
    state().updateLayer('0', { opacity: 1 })
    state().selectLayer(null)
    state().selectLayer('0')
    expect(state().history).toBe(before)
    state().updateLayer('0', { opacity: 0.5 })
    expect(state().history.past).toHaveLength(1)
    expect(state().history.future).toHaveLength(0)
    expect(state().history.snapshots).toBe(before.snapshots)
    expect(state().history.baseLabel).toBe('打开')
    expect(state().history.timelineSnapshot).toBeNull()
    state().undo()
    expect(state().layers[0].opacity).toBe(1)
    expect(state().customFps).toBeNull()
    expect(state().customFrames).toBeNull()
    state().redo()
    expect(state().layers[0].opacity).toBe(0.5)
  })

  it('重命名当前快照更新分支的基线名称，默认名称不冲突', () => {
    const firstId = state().createHistorySnapshot()
    state().createHistorySnapshot()
    expect(state().history.snapshots!.map(snapshot => snapshot.name)).toEqual(['打开', '快照 1', '快照 2'])
    state().restoreHistorySnapshot(firstId)
    const before = state().history
    state().renameHistorySnapshot(firstId, ' ')
    state().renameHistorySnapshot('missing', '改名')
    expect(state().history).toBe(before)
    state().renameHistorySnapshot(firstId, '  备选方案  ')
    expect(state().history.activeSnapshotLabel).toBe('备选方案')
    state().updateLayer('0', { opacity: 0.2 })
    expect(state().history.baseLabel).toBe('备选方案')
  })

  it('删除当前快照不回退画面、不破坏旧时间线，撤销仍能回去', () => {
    makeEdits()
    const opened = openSnapshotId()
    state().restoreHistorySnapshot(opened)
    const before = state()
    state().deleteHistorySnapshot(opened)
    expect(state().layers).toBe(before.layers)
    expect(state().history.snapshots).toEqual([])
    expect(state().history.activeSnapshotId).toBe(opened)
    expect(state().history.activeSnapshotLabel).toBe('打开')
    expect(state().history.timelineSnapshot).toBe(before.history.timelineSnapshot)
    expect(state().history.past).toBe(before.history.past)
    expect(state().canUndo).toBe(true)
    state().undo()
    expect(state().layers[0].opacity).toBe(0.8)
    expect(state().customFps).toBe(60)
    expect(state().history.activeSnapshotId).toBeNull()
  })

  it('在已删除的当前快照上编辑仍正确另起分支', () => {
    makeEdits()
    const opened = openSnapshotId()
    state().restoreHistorySnapshot(opened)
    state().deleteHistorySnapshot(opened)
    state().updateLayer('0', { name: '快照分支' })
    expect(state().history.baseLabel).toBe('打开')
    expect(state().history.past).toHaveLength(1)
    expect(state().history.timelineSnapshot).toBeNull()
    state().undo()
    expect(state().layers[0].name).toBe('avatar')
    expect(state().layers[0].opacity).toBe(1)
  })

  it('清空快照视图中的历史只保留当前画面和快照，不暗中恢复旧时间线', () => {
    makeEdits()
    state().restoreHistorySnapshot(openSnapshotId())
    const before = state()
    state().clearHistory()
    expect(state().layers).toBe(before.layers)
    expect(state().history.past).toEqual([])
    expect(state().history.future).toEqual([])
    expect(state().history.snapshots).toBe(before.history.snapshots)
    expect(state().history.timelineSnapshot).toBeNull()
    expect(state().history.activeSnapshotId).toBeNull()
    expect(state().canUndo).toBe(false)
  })

  it.each(['replace', 'reset'] as const)('换文档与重置立即隔离旧快照：%s', action => {
    makeEdits()
    const id = openSnapshotId()
    state().restoreHistorySnapshot(id)
    if (action === 'replace') state().setVideoItem(createVideo('other'))
    else state().reset()
    expect(state().history.snapshots).toEqual([])
    expect(state().history.timelineSnapshot).toBeNull()
    expect(state().history.activeSnapshotId).toBeNull()
    expect(state().history.past).toEqual([])
    expect(state().history.future).toEqual([])
    const fresh = state()
    state().restoreHistorySnapshot(id)
    state().renameHistorySnapshot(id, '旧文档')
    state().deleteHistorySnapshot(id)
    expect(state()).toBe(fresh)
  })

  it('新文档的打开快照不携带旧文档的帧设置、资源替换和关键帧', () => {
    makeEdits()
    state().setSlotConfig('avatar', { type: 'image', name: 'avatar', value: 'replaced' })
    state().setDetectedSlots(['avatar'])
    state().addKeyframe({ frameIndex: 3, value: 0.5, easing: 'linear' })
    state().selectKeyframe(state().keyframes[0].id)
    state().setRendererMode('high-performance')
    state().setSpeed(2)
    state().setPlaying(true)
    const nextVideo = createVideo('other')
    state().setVideoItem(nextVideo)
    state().initializeHistory()
    expect(state().videoItem).toBe(nextVideo)
    expect(state().originalBuffer).toBeNull()
    expect(state().customFps).toBeNull()
    expect(state().customFrames).toBeNull()
    expect(state().slotConfigs).toEqual({})
    expect(state().detectedSlots).toEqual([])
    expect(state().audioResources.size).toBe(0)
    expect(state().imageResources.has('avatar')).toBe(false)
    expect(state().keyframes).toEqual([])
    expect(state().selectedKeyframeIds).toEqual([])
    expect(state().playback).toMatchObject({ totalFrames: 24, fps: 24, currentFrame: 0, isPlaying: false, speed: 2 })
    expect(state().rendererMode).toBe('high-performance')
    const opened = state().history.snapshots![0].snapshot
    expect(opened.videoItem).toBe(nextVideo)
    expect(opened.customFps).toBeNull()
    expect(opened.customFrames).toBeNull()
    expect(opened.keyframes).toEqual([])
    expect(opened.slotConfigs).toEqual({})
    expect(opened.audioResources.size).toBe(0)
  })

  it('重复设置同一源对象不重置历史、当前快照或正在进行的画布操作', () => {
    makeEdits()
    state().restoreHistorySnapshot(openSnapshotId())
    state().beginCanvasTransform('0')
    state().previewCanvasTransform('0', normalizeCanvasTransform({ x: 50 }))
    const before = state()
    state().setVideoItem(before.videoItem)
    expect(state()).toBe(before)
    state().endCanvasTransform(true)
    expect(state().layers[0].canvasTransform!.x).toBe(50)
    expect(state().history.past).toHaveLength(1)
  })

  it('移除当前文档时清空源数据，不留下旧画面或播放状态', () => {
    makeEdits()
    state().setVideoItem(null)
    expect(state().params).toBeNull()
    expect(state().layers).toEqual([])
    expect(state().imageResources.size).toBe(0)
    expect(state().audioResources.size).toBe(0)
    expect(state().playback).toMatchObject({ totalFrames: 0, currentFrame: 0, isPlaying: false })
    expect(state().history.snapshots).toEqual([])
  })
})

describe('历史还原的数据完整性与画布事务', () => {
  it('还原图层、音频、图片字节和插槽，应用后的数据与快照互不污染', () => {
    const id = state().createHistorySnapshot('完整资源')
    state().removeImageResource('avatar')
    state().removeAudioResource('music')
    state().setSlotConfig('avatar', { type: 'image', name: 'avatar', value: 'replaced' })
    state().deleteLayer('0')
    state().restoreHistorySnapshot(id)
    expect(state().layers[0].imageKey).toBe('avatar')
    expect(state().selectedLayerId).toBe('0')
    expect(state().imageResources.get('avatar')!.data).toEqual(new Uint8Array([1, 2, 3]))
    expect(state().audioResources.get('music')!.data).toEqual(new Uint8Array([4, 5]))
    expect(state().slotConfigs).toEqual({})
    state().imageResources.get('avatar')!.data[0] = 99
    state().audioResources.get('music')!.data[0] = 88
    state().layers[0].sprites!.frames[0].transform.tx = 999
    state().restoreHistorySnapshot(id)
    expect(state().imageResources.get('avatar')!.data[0]).toBe(1)
    expect(state().audioResources.get('music')!.data[0]).toBe(4)
    expect(state().layers[0].sprites!.frames[0].transform.tx).toBe(0)
  })

  it('资源重命名后的跳转和重做同步还原源资源键，不改变原始对象', () => {
    const original = state().videoItem!
    expect(state().renameImageResourceKey('avatar', 'renamed')).toBe(true)
    const renamed = state().videoItem!
    expect(original.buffers.avatar).toBeDefined()
    expect(original.buffers.renamed).toBeUndefined()
    expect(original.movie.sprites[0].imageKey).toBe('avatar')
    expect(renamed.buffers.avatar).toBeUndefined()
    state().jumpToHistory(0)
    expect(state().videoItem).toBe(original)
    expect(state().videoItem!.buffers.avatar).toBeDefined()
    expect(state().layers[0].imageKey).toBe('avatar')
    expect(state().imageResources.has('avatar')).toBe(true)
    state().redo()
    expect(state().videoItem).toBe(renamed)
    expect(state().videoItem!.buffers.renamed).toBeDefined()
    expect(state().layers[0].imageKey).toBe('renamed')
    expect(state().imageResources.has('renamed')).toBe(true)
  })

  it('跳转同步恢复总帧数和帧率，暂停播放并将游标截到有效范围', () => {
    state().setCustomFrames(6)
    state().setCustomFps(12)
    state().jumpToHistory(0)
    state().setCurrentFrame(20)
    state().setPlaying(true)
    state().jumpToHistory(2)
    expect(state().playback).toMatchObject({ totalFrames: 6, fps: 12, currentFrame: 5, isPlaying: false })
    state().jumpToHistory(0)
    expect(state().playback).toMatchObject({ totalFrames: 24, fps: 24, currentFrame: 5, isPlaying: false })
  })

  it('未提交画布拖动在跳转时取消，不留下隐形步骤或被后续鼠标事件覆盖', () => {
    makeEdits()
    state().beginCanvasTransform('0')
    state().previewCanvasTransform('0', normalizeCanvasTransform({ x: 99 }))
    state().jumpToHistory(0)
    expect(state().isCanvasTransforming).toBe(false)
    expect(state().layers[0].canvasTransform).toBeUndefined()
    expect(state().history.future).toHaveLength(3)
    state().endCanvasTransform(true)
    state().jumpToHistory(3)
    expect(state().layers[0].canvasTransform).toBeUndefined()
    expect(state().history.past).toHaveLength(3)
    expect(state().customFps).toBe(60)
  })

  it('恢复快照和删除状态均取消正在预览的拖动', () => {
    makeEdits()
    state().beginCanvasTransform('0')
    state().previewCanvasTransform('0', normalizeCanvasTransform({ x: 50 }))
    state().restoreHistorySnapshot(openSnapshotId())
    expect(state().isCanvasTransforming).toBe(false)
    state().undo()
    expect(state().layers[0].canvasTransform).toBeUndefined()
    state().beginCanvasTransform('0')
    state().previewCanvasTransform('0', normalizeCanvasTransform({ x: 70 }))
    state().deleteHistoryState(2)
    state().endCanvasTransform(true)
    expect(state().isCanvasTransforming).toBe(false)
    expect(state().layers[0].canvasTransform).toBeUndefined()
    expect(state().history.past).toHaveLength(1)
  })

  it('创建快照先完成当前拖动，快照记下已提交的画面', () => {
    state().beginCanvasTransform('0')
    state().previewCanvasTransform('0', normalizeCanvasTransform({ x: 50 }))
    const id = state().createHistorySnapshot()
    expect(state().isCanvasTransforming).toBe(false)
    expect(state().history.past).toHaveLength(1)
    state().undo()
    expect(state().layers[0].canvasTransform).toBeUndefined()
    state().restoreHistorySnapshot(id)
    expect(state().layers[0].canvasTransform!.x).toBe(50)
  })

  it('全局关键帧的新增、修改和删除均可以跳转还原，纯选中不增加历史', () => {
    state().addKeyframe({ frameIndex: 3, value: { x: 2, y: 4 }, easing: 'linear' })
    const id = state().keyframes[0].id
    state().selectKeyframe(id)
    expect(state().history.past).toHaveLength(1)
    state().updateKeyframe(id, { value: { x: 5, y: 6 } })
    state().deleteKeyframe(id)
    expect(state().keyframes).toEqual([])
    state().jumpToHistory(1)
    expect(state().keyframes[0].value).toEqual({ x: 2, y: 4 })
    expect(state().selectedKeyframeIds).toEqual([id])
    state().jumpToHistory(2)
    expect(state().keyframes[0].value).toEqual({ x: 5, y: 6 })
    state().jumpToHistory(0)
    expect(state().keyframes).toEqual([])
  })

  it('附加动画关键帧与原始逐帧动画都随快照恢复', () => {
    const originalFrames = structuredClone(state().layers[0].sprites!.frames)
    expect(state().setAnimationValue('0', 'position', { x: 30, y: 40 }, 5).changed).toBe(true)
    const id = state().createHistorySnapshot('关键帧')
    const keyframeId = state().layers[0].animationTracks!.position.keyframes.find(keyframe => keyframe.frameIndex === 5)!.id
    state().deleteAnimationKeyframes('0', 'position', [keyframeId])
    state().restoreHistorySnapshot(id)
    expect(state().layers[0].animationTracks!.position.keyframes.find(keyframe => keyframe.id === keyframeId)!.value).toEqual({ x: 30, y: 40 })
    expect(state().layers[0].sprites!.frames).toEqual(originalFrames)
    state().jumpToHistory(0)
    expect(state().layers[0].animationTracks).toBeUndefined()
    expect(state().layers[0].sprites!.frames).toEqual(originalFrames)
  })
})
