import type { useEditorStore } from '@/stores'
import type { MovieParams } from '@/types'
import { SVGAOptimizer, type OptimizationConfig, type OptimizationStats } from './optimizer'
import { SVGAParser } from './parser'

type ExportState = Pick<ReturnType<typeof useEditorStore.getState>,
  'videoItem' | 'originalBuffer' | 'params' | 'customFps' | 'customFrames' |
  'layers' | 'imageResources' | 'slotConfigs' | 'compressionConfig' | 'optimizationConfig' | 'audioResources'>

/** Playback, selection and viewport changes must not invalidate generated bytes. */
export function captureExportInputs(state: ExportState): readonly unknown[] {
  return [state.videoItem, state.originalBuffer, state.params, state.customFps, state.customFrames,
    state.layers, state.imageResources, state.slotConfigs, state.compressionConfig, state.optimizationConfig, state.audioResources]
}

export function sameExportInputs(a: readonly unknown[], b: readonly unknown[]): boolean {
  return a.length === b.length && a.every((value, index) => value === b[index])
}

/** 输入变化属于结果失效，与编码或写盘失败分开提示。 */
export class ExportInputsChangedError extends Error {
  constructor() {
    super('编辑内容或导出配置已变化，请重新生成预览。')
    this.name = 'ExportInputsChangedError'
  }
}

export interface ExportPreviewResult {
  baseline: Blob
  optimized: Blob
  sourceBytes: number
  params: MovieParams
  stats: OptimizationStats
  warnings: string[]
}

export async function generateExportPreview(
  buildBaseline: () => Promise<Blob>,
  config: OptimizationConfig,
  sourceBytes: number,
  params: MovieParams,
  onPhase?: (phase: string) => void
): Promise<ExportPreviewResult> {
  if (!Number.isFinite(params.fps) || params.fps <= 0 || !Number.isInteger(params.frames) || params.frames < 1) {
    throw new Error('帧率或总帧数无效，请先检查动画参数')
  }
  onPhase?.('正在生成当前编辑的未优化副本…')
  const baseline = await buildBaseline()
  if (!baseline.size) throw new Error('未优化副本为空')
  onPhase?.('正在优化并计算实际文件大小…')
  // Each job owns its optimizer and statistics; no shared singleton races.
  const optimizer = new SVGAOptimizer()
  const optimized = await optimizer.optimize(await baseline.arrayBuffer(), config, (done, total) => onPhase?.(`正在压缩图片 ${done} / ${total}…`))
  if (!optimized.size) throw new Error('优化结果为空')
  const stats = {
    ...optimizer.getStats(),
    originalSize: baseline.size,
    optimizedSize: optimized.size,
    reductionPercent: Math.round((1 - optimized.size / baseline.size) * 1000) / 10
  }
  const warnings: string[] = [...(stats.warnings ?? [])]
  if (config.enabled && config.image.pngColors && config.image.format !== 'webp') warnings.push(`PNG ${config.image.pngColors} 色量化包含透明度，注意检查渐变、辉光和抗锯齿边缘。`)
  if (optimized.size > baseline.size) warnings.push('本次优化使文件变大，可降低优化强度或保存未优化副本。')
  if (config.enabled && config.image.format !== 'png') warnings.push('当前配置可能输出 WebP 图片，请在目标 SVGA 播放器上验证兼容性。')
  if (config.enabled && (config.image.resizeEnabled || config.frames.simplify || config.frames.removeInvisible || config.frames.precision < 6)) {
    warnings.push('当前配置包含缩放或帧数据精简，请重点检查边缘、遮罩和动画细节。')
  }
  return { baseline, optimized, sourceBytes, params: { ...params }, stats, warnings }
}

/** Isolated decoding owns every URL, including failed image decodes. */
export async function loadExportPreviewVideo(blob: Blob) {
  const urls: string[] = []
  const dispose = () => urls.splice(0).forEach((url) => URL.revokeObjectURL(url))
  try {
    const video = await new SVGAParser().parse(await blob.arrayBuffer(), { onImageUrlCreated: (url) => urls.push(url) })
    const params = video.movie.params
    if (!params || !Number.isFinite(params.viewBoxWidth) || !Number.isFinite(params.viewBoxHeight)
      || params.viewBoxWidth < 1 || params.viewBoxHeight < 1 || !Number.isFinite(params.frames) || params.frames < 1) {
      throw new Error('无法预览：动画尺寸或帧数无效')
    }
    if (params.viewBoxWidth * params.viewBoxHeight > 4_194_304 || params.viewBoxWidth > 8192 || params.viewBoxHeight > 8192) {
      throw new Error('画布过大，已跳过动画预览；仍可查看体积并保存文件')
    }
    const missing = (video.movie.sprites || []).some(sprite => sprite.imageKey && video.buffers?.[sprite.imageKey] && !video.images[sprite.imageKey])
    return { video, dispose, warning: missing ? '部分图片解码失败，预览可能不完整，请在目标播放器验证。' : null }
  } catch (error) {
    dispose()
    throw error
  }
}
