name: Actions Smoke Test

on:
  push:
  workflow_dispatch:
  repository_dispatch:
    types:
      - actions-smoke-test

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "Actions queue is working"
          echo "Ref: $GITHUB_REF"
